title: Sandeep Pandey | AI Research
description: Research Scientist specializing in Large Language Models, Speech Processing & AI-driven Financial Automation
remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
header_pages:
  - bio.md
  - blog.md
author:
  name: Sandeep Pandey
  email: sandeeppandey456@gmail.com
social:
  linkedin: sandeep-pandey-43790921
  scholar: NveAdp8AAAAJ
